### ISSUE TITLE
"-o output only the temperature value", but no switch option

### ISSUE THREAD

**Issue by jimbolaya** [froonix/pcsensor-temper#9]
Are there plans to add the output only the temperature value option in the future?

pcsensor -o
pcsensor: invalid option -- 'o'
pcsensor version 1.1.0
USAGE: pcsensor [options] <arguments>
  ARGUMENTS:
  OPTIONS:
    -h help
    -v verbose
    -n[i] use device number i (0 is the first one found on the bus)
    -l[n] loop every 'n' seconds, default value is 5
    -c output only in Celsius
    -f output only in Fahrenheit
    -a[n] increase or decrease temperature in 'n' degrees for device calibration
    -m output for mrtg integration
    -o output only the temperature value

**Comment by killerbees19** [comment]
Looks like a typo in the help output… :-)

Try `-p` (_"plain"_) in combination with `-c`/`-f`, that works. I'll fix it later.

**Comment by jimbolaya** [comment]
Yes, works as hoped.

**Comment by killerbees19** [comment]
Thanks for your bugreport, the updated version is online.

The experimental Debian Jessie package will be uploaded to my repository in ~7 hours.
